services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
    networks:
      - user-network
    healthcheck:
      test: ['CMD', 'echo', 'test']
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    container_name: message_broker
    ports:
      - '9092:9092'
      - '9094:9094'
    networks:
      - user-network

  mongo:
    image: mongo:latest
    container_name: user_data
    env_file:
      - ../.env
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - user-network
    restart: unless-stopped

networks:
  user-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
