name: Integration

on:
  push:
    branches:
      - '**'

permissions:
  actions: read
  contents: read

jobs:
  Integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Install dependencies
        run: pnpm install

      - name: Set NX Cloud SHAs
        id: nx-cloud
        run: |
          set +e
          nrwl/nx-set-shas@v4
          echo "NX_CLOUD_SUCCESS=$?" >> $GITHUB_ENV
          set -e

      - name: Check formatting
        run: pnpm format-check

      - name: Check Linting
        env:
          NX_CLOUD_INTEGRATION: ${{ secrets.NX_CLOUD_INTEGRATION }}
        run: |
          if [ "${{ env.NX_CLOUD_SUCCESS }}" == "1" ]; then
            echo "NX Cloud integration failed. Running lint-check without it."
            pnpm lint-check --skip-nx-cloud
          else
            pnpm lint-check
          fi
