name: Update diagrams

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'architecture/structurizr/workspace.dsl'
      - 'architecture/structurizr/*.py'

jobs:
  update-diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install PlantUML
        run: |
          sudo apt-get install -y plantuml

      - name: Install Structurizr CLI
        run: |
          curl -L -o structurizr-cli.zip https://github.com/structurizr/cli/releases/download/v1.34.0/structurizr-cli-1.34.0.zip
          unzip structurizr-cli.zip -d structurizr-cli
          echo "$(pwd)/structurizr-cli" >> $GITHUB_PATH

      - name: Generate PlantUML files from Structurizr DSL
        run: |
          structurizr.sh export -workspace structurizr/workspace.dsl -format plantuml
        working-directory: architecture

      - name: Update diagrams
        run: |
          for puml in structurizr/*.puml; do
            plantuml -tpng "$puml"
          done
          mkdir -p diagrams
          mv structurizr/*.png diagrams/
        working-directory: architecture

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add diagrams/*.png
          git commit -m "Update diagrams" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: architecture
